services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    environment:
      CI_ENVIRONMENT: development
      app.baseURL: http://localhost:8080/
    volumes:
      - ./:/var/www/html
